### ISSUE TITLE
multiple displays

### ISSUE THREAD

**Issue by vanderbreye** [kkeller/Nokia5110#2]
I tried connecting a second and third display to the BBB, but it seems as if its impossible to write to each 5110 seperately.
although i'm setting it for each display (pin 17 on lcd.PIN_SCE & pin 14 on lcd2.PIN_SCE) the data is always written to ALL displays..
shouldn't it be possible to write to each display independently?

my code/wiring:

//lcd1.LED
  lcd1.PIN_SCLK = "P9_22";
  lcd1.PIN_SDIN = "P9_21"; //MOSI
  lcd1.PIN_DC = "P9_15";
  lcd1.PIN_RESET = "P9_16";
  lcd1.PIN_SCE = "P9_17";
//lcd1.GND
//lcd1.VCC

  lcd2.PIN_SCLK = "P9_22";
  lcd2.PIN_SDIN = "P9_21"; //MOSI
  lcd2.PIN_DC = "P9_15";
  lcd2.PIN_RESET = "P9_16";
  lcd2.PIN_SCE = "P9_14"; //different IO than lcd1!

**Comment by kkeller** [comment]
The LCD_5110.js file is not written to enable multiple 5110s. Without seeing your entire program it is hard to guess but I suspect the select pins to the second and third LCDs are always enabled and therefore get the data/write commands at the same time as the first LCD. You are welcome to write and submit code to the LCD_5110.js file to distinguish between multiple LCDs.

A quick hack that _might_ work would be to assign the lcd select pin (lcd.PIN_SCE = "P9_xx";) to a non-used pin then enable the proper LCD before calling the lcd routines. If you do this, make sure you only enable the one LCD you want to write to. If you leave multiple LCDs enabled, all will get the data. You might need to enable all the LCDs during the initialization (  lcd.setup();   ) call.

Something like this...
....
digitalWrite(lcd1.PIN_SCE, LOW);
lcd.string('HELLO WORLD!');
digitalWrite(lcd1.PIN_SCE, HIGH);
...

You might need to enable all the LCDs during the initialization (  lcd.setup();   ) call.

Ken -
